# Site settings
title: Rounak's Vitae
email: rounakdatta12@gmail.com
description: > 
	Being the other side of professional
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  rounakdatta

# Build settings
sass:
	sass_dir: -sass
include: ['_pages']
krmadown:
	input: GFM
