# Site settings
title: Vitae
email: rounakdatta12@gmail.com
description: > 
 #!/bin/blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rounakdatta.github.io" # the base hostname & protocol for your site
github_username:  rounakdatta

# Build settings
markdown: kramdown
