# Site settings
title: Rounak's Vitae
email: rounakdatta12@gmail.com
description: > 
 My essentials in a gist for you
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  rounakdatta

# Build settings
markdown: kramdown
