baseURL = ""
languageCode = "en-us"
title = "Rounak's Blog"
theme = "er"
copyright = "Written and published right from Emacs Org-mode."

canonifyURLs = true

RemovePathAccents = true
enableEmoji = true
enableGitInfo = true

disableFastRender = true        # Hugo 0.30

pygmentsStyle = "pygments"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # This is *necessary* for ox-hugo to work well with Hugo 0.60.0+
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[Taxonomies]
  category = "categories" # SINGULAR = "PLURAL"
  tag = "tags"

[Author]
  name = "Rounak Datta"

[Social]
  github = "rounakdatta"

[[menu.main]]
  weight = 1
  identifier = "about"
  name = "About"
  url = "/about"
