baseURL = ""
languageCode = "en-us"
title = "Rounak's Blog"
theme = "er"
copyright = "Written and published right from Emacs Org-mode."

canonifyURLs = true

RemovePathAccents = true
enableEmoji = true
enableGitInfo = true

disableFastRender = true        # Hugo 0.30

pygmentsCodeFences = true       # This applies to Chroma too.
pygmentsUseClasses = true       # This applies to Chroma too.

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # This is *necessary* for ox-hugo to work well with Hugo 0.60.0+

[Taxonomies]
  category = "categories" # SINGULAR = "PLURAL"
  tag = "tags"

[Author]
  name = "Rounak Datta"

[Social]
  github = "rounakdatta"

[[menu.main]]
  weight = 1
  identifier = "about"
  name = "About"
  url = "/about"
